version: "3.5"

services:

  app:
    image: davetorres/base-lumen:latest
    ports:
      - "${DOCKER_APP_PORT}:80"
    volumes:
      - .:/var/www/html
#      - .services/app:/var/www/services
#    entrypoint: /var/www/services/entrypoint.sh
    networks:
      - overlay

#  ngrok:
#    image: wernight/ngrok:latest
#    ports:
#      - "${DOCKER_NGROK_PORT}:4040"
#    environment:
#      NGROK_PROTOCOL: "http"
#      NGROK_PORT: "api:80"
#      NGROK_AUTH: "${DOCKER_NGROK_AUTH}"
#      NGROK_SUBDOMAIN: "${DOCKER_NGROK_SUBDOMAIN}"
#    depends_on:
#      - app
#    networks:
#      - overlay
#
#  mysql:
#    image: 'mysql:8'
#    ports:
#      - '${DOCKER_DB_PORT}:3306'
#    volumes:
#      - './.services/mysql/${DB_DATABASE}:/var/lib/mysql'
#    command: '--default-authentication-plugin=mysql_native_password'
#    environment:
#      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_USER: '${DB_USERNAME}'
#      MYSQL_DATABASE: "${DB_DATABASE}"
#      MYSQL_PASSWORD: '${DB_PASSWORD}'
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 1s
#      timeout: 3s
#      retries: 60
#    networks:
#      - overlay
#
#  phpmyadmin:
#    image: 'phpmyadmin/phpmyadmin:4.7'
#    ports:
#      - '${DOCKER_DB_ADMIN_PORT}:80'
#    environment:
#      PMA_ARBITRARY: 1
#      PMA_HOSTS: '${DB_HOST}'
#      PMA_USER: '${DB_USERNAME}'
#      PMA_PASSWORD: '${DB_PASSWORD}'
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://phpmyadmin"]
#      interval: 1s
#      timeout: 3s
#      retries: 60
#    depends_on:
#      - mysql
#    networks:
#      - overlay

networks:
  overlay:
