stack:
  commands:
    up:
      description: Spin up the stack
      commands: docker-compose up -d
    down:
      description: Spin down the stack
      commands: docker-compose down
    dev:
      description: Build for development environment
      commands: |
        export COMPOSE_INTERACTIVE_NO_CLI=1
        sail npm run dev
    prod:
      description: Build for development environment
      commands: |
        export COMPOSE_INTERACTIVE_NO_CLI=1
        sail npm run prod
    watch:
      description: Start the npm watcher inside the container
      commands: |
        export COMPOSE_INTERACTIVE_NO_CLI=1
        sail npm run watch
    npm:
      install:
        description: Run npm install inside the container
        commands: |
          export COMPOSE_INTERACTIVE_NO_CLI=1
          sail npm install
    db:
      open:
        description: Open phpmyadmin in your browser (works on mac)
        commands: open http://127.0.0.1:8043
      migrate:
        default:
          description: Migrate the database through the app container
          commands: |
            export COMPOSE_INTERACTIVE_NO_CLI=1
            sail artisan migrate
          rollback:
            description: Roll back the database
            commands: |
              export COMPOSE_INTERACTIVE_NO_CLI=1
              sail artisan migrate:rollback
      seed:
        dev:
          description: Seed some development data
          commands: |
            export COMPOSE_INTERACTIVE_NO_CLI=1
            sail artisan db:seed --class=DevDataSeeder
    docker:
      stop:
        description: Stop all docker containers on this system
        commands: docker stop $(docker ps -aq)
      rm:
        description: Remove all containers on this system
        commands: docker rm $(docker ps -aq)
      rmi:
        description: Remove all images on this system
        commands: docker rmi $(docker images -aq)
