export default {
    LOCAL_ACCESS_TOKEN_KEY: 'BUDGET_ACCESS_TOKEN',
    LOCAL_REFRESH_TOKEN_KEY: 'BUDGET_REFRESH_TOKEN',
    AUTH_USER_LOCKED: 'AUTH_USER_LOCKED',
    API_URL: env.VUE_APP_GRAPHQL_HTTP,
    API_API_URL: env.VUE_APP_API_HTTP,
    VIEW_GROUPS: 'groups',
    VIEW_INCOMES: 'incomes',
    AVATAR_BASE_PATH: env.AVATAR_BASE_PATH
}
